[package]
name = "iso9796_rsa"
version = "0.1.1"
edition = "2021"

[dependencies]
eyre = "0.6.12"
rsa = { version = "0.9.6", features = ["sha1", "sha2", "hazmat"] }
sha1 = "0.10.6"
zeroize = "1.8.1"


[dev-dependencies]
rand = "0.8"